//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public string membership_type { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> renew_duration { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<System.DateTime> renew_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
    
        public virtual member member { get; set; }
    }
}
