//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public member()
        {
            this.bills = new HashSet<bill>();
            this.renews = new HashSet<renew>();
        }
    
        public int id { get; set; }
        public string fullname { get; set; }
        public System.DateTime dob { get; set; }
        public string gender { get; set; }
        public string contact_number { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string postcode { get; set; }
        public string occupation { get; set; }
        public int membership_type { get; set; }
        public string membership_number { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string photo { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<renew> renews { get; set; }
    }
}
