//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_member_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public new_member_table()
        {
            this.renews = new HashSet<renew>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public string contact_number { get; set; }
        public string address { get; set; }
        public string post_code { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string country { get; set; }
        public string occupation { get; set; }
        public string membership_photo { get; set; }
        public string membership_type_forign { get; set; }
        public int number_of_month { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
    
        public virtual membership_report_table membership_report_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<renew> renews { get; set; }
    }
}
