//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class renew
    {
        public int id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<System.DateTime> renew_date { get; set; }
    
        public virtual new_member_table new_member_table { get; set; }
    }
}
