//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_member_table
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public decimal contact_number { get; set; }
        public string address { get; set; }
        public string post_code { get; set; }
        public string age { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string country { get; set; }
        public string occupation { get; set; }
        public byte[] membership_photo { get; set; }
        public string membership_type_forign { get; set; }
    
        public virtual membership_report_table membership_report_table { get; set; }
        public virtual membership_type_table membership_type_table { get; set; }
    }
}
